function [EQU]=equ(i,j,A,B,C,D,E,stepx,stepy)
EQU=[num2str(A),'*(pi',num2str(i+1),'j',num2str(j),'+pi',num2str(i-1),'j',num2str(j),'-2*pi',num2str(i),'j',num2str(j),')/',num2str(stepx),'^2'...
    '+',num2str(B),'*(pi',num2str(i),'j',num2str(j+1),'+pi',num2str(i),'j',num2str(j-1),'-2*pi',num2str(i),'j',num2str(j),')/',num2str(stepy),'^2'...
    '+',num2str(C),'*(pi',num2str(i+1),'j',num2str(j),'-pi',num2str(i-1),'j',num2str(j),')/2/',num2str(stepx)...
     '+',num2str(D),'*(pi',num2str(i),'j',num2str(j+1),'-pi',num2str(i),'j',num2str(j-1),')/2/',num2str(stepy)...
     '-',num2str(E)];
